Repository torrust/torrust-index-gui, pull requests merged in 2023-11, with the labels that each got.

#306 Adds tests for generating the magnet link on torrents list page
  components/torrent/TorrentList.vue
  components/torrent/TorrentTable.vue
  cypress/e2e/contexts/torrent/specs/list/magnet_link.cy.ts
  cypress/support/commands.ts
  pages/torrents.vue
Labels: Needs Rebase

#378 Refactor `publish_docker_image.yml` workflow
  .github/workflows/container.yaml
  .github/workflows/publish_docker_image.yml
  .github/workflows/test_docker_build.yml
  Containerfile
  compose.yaml
  contrib/dev-tools/container/docker-build-debug.sh
  contrib/dev-tools/container/docker-run-local.sh
  contrib/dev-tools/container/docker-run-public.sh
Labels: Code Cleanup / Refactoring, Build | Project System, - Developer -, Quality & Assurance

#382 Containerization documentation
  Containerfile
  contrib/dev-tools/container/e2e/sqlite/e2e-env-up.sh
  docs/containers.md
  docs/index.md
  project-words.txt
Labels: Continuous Integration, - Developer -, Portability, Quality & Assurance

#388 Use NITRO env vars for `NITRO_HOST` and `NITRO_HOST`
  Containerfile
  compose.yaml
  contrib/dev-tools/container/docker-run-local.sh
  contrib/dev-tools/container/docker-run-public.sh
  docs/containers.md
Labels: Documentation, Code Cleanup / Refactoring, - Admin -, - Developer -

#394 Review docs
  README.md
  docs/containerization_guide.md
  docs/development_guide.md
  docs/index.md
  docs/release_process_guide.md
  docs/user_guide.md
Labels: Documentation, - Admin -, - Developer -, - User -, - Contributor -
