Repository torrust/torrust-index-gui, pull requests merged in 2024-02, with the labels that each got.

#472 Update dependencies
  app.vue
  components/TorrustSelect.vue
  components/authentication/AuthenticationForm.vue
  components/navigation/NavigationBar.vue
  components/registration/RegistrationForm.vue
  components/torrent/TorrentActionCard.vue
  components/torrent/TorrentCommentTab.vue
  components/torrent/TorrentCreatedByTab.vue
  components/torrent/TorrentCreationDateTab.vue
  components/torrent/TorrentDescriptionTab.vue
  components/torrent/TorrentDetails.vue
  components/torrent/TorrentEncodingTab.vue
  components/torrent/TorrentFilesTab.vue
  components/torrent/TorrentList.vue
  components/torrent/TorrentListTorrentDetails.vue
  components/torrent/TorrentTable.vue
  components/torrent/TorrentTrackersTab.vue
  composables/states.ts
  cypress/e2e/contexts/torrent/specs/details/magnet_link.cy.ts
  cypress/e2e/contexts/torrent/specs/download.cy.ts
  cypress/e2e/contexts/torrent/specs/list/magnet_link.cy.ts
  cypress/e2e/contexts/torrent/specs/list/no_torrents_to_display.cy.ts
  cypress/e2e/contexts/torrent/specs/upload.cy.ts
  cypress/e2e/contexts/torrent/tasks.ts
  cypress/e2e/contexts/user/tasks.ts
  cypress/support/commands.ts
  package-lock.json
  pages/admin/settings.vue
  pages/admin/settings/backend.vue
  pages/admin/settings/tags.vue
  pages/torrent/edit/[infoHash].vue
  pages/torrents.vue
  pages/upload.vue
  plugins/notifications.client.ts
  tsconfig.json
Labels: Dependencies

#475 Remove torrent list page heading
  pages/torrents.vue
Labels: - User -, UX

#476 Add torrent title in `TorrentDetails` component
  components/torrent/TorrentDetails.vue
Labels: UX, UI

#477 Remove duplicate filter in navigation bar
  components/navigation/NavigationBar.vue
Labels: - User -, UX, UI

#480 On torrent table layout add an action to navigate to torrent details
  components/torrent/TorrentTable.vue
Labels: - User -, UX, UI

#481 Show error when proxied image cannot be loaded
  package-lock.json
  package.json
  src/domain/services/sanitizer.ts
Labels: - User -, UX

#487 Rename button "download torrent" to "download private torrent" when the tracker is in close mode
  components/torrent/TorrentActionCard.vue
  composables/helpers.ts
  cypress/e2e/contexts/user/tasks.ts
Labels: Enhancement / Feature Request, - User -, Bug

#488 Update dependencies
  components/torrent/TorrentActionCard.vue
  package-lock.json
  package.json
Labels: Dependencies

#298 E2E test for deleting tags
  cypress.config.ts
  cypress/e2e/contexts/tag/commands.ts
  cypress/e2e/contexts/tag/random_data.ts
  cypress/e2e/contexts/tag/specs/delete.cy.ts
  cypress/e2e/contexts/tag/tasks.ts
  cypress/support/commands.ts
  pages/admin/settings/tags.vue
Labels: Needs Rebase

#458 docs: [#457] update README file
  README.md
Labels: Needs Rebase
