Repository torrust/torrust-index-gui, pull requests merged in 2024-04, with the labels that each got.

#416 feat: [#401] update footer
  app.vue
  components/license/License.vue
  composables/useFetchForTextFiles.ts
  pages/license.vue
  public/COPYRIGHT.md
  public/LICENSE-AGPL_3_0.md
  public/LICENSE-MIT_0.md
  public/contributor_agreement_v01.md
  public/legacy_exception.md
  src/domain/services/sanitizer.ts
Labels: Needs Rebase

#510 chore: update deps
  package-lock.json
  package.json
Labels: Dependencies

#530 refactor:[#529] remove seeders/leechers column from Tracker Tab
  components/torrent/TorrentTrackersTab.vue
Labels: - User -, UX

#531 fix:[#525] add break-words to torrent component tab
  components/torrent/TorrentCommentTab.vue
  components/torrent/TorrentCreatedByTab.vue
  components/torrent/TorrentCreationDateTab.vue
  components/torrent/TorrentDescriptionTab.vue
  components/torrent/TorrentEncodingTab.vue
Labels: Bug, UI

#535 fix:[#525] more efficient solution
  components/Markdown.vue
  components/torrent/TorrentCommentTab.vue
  components/torrent/TorrentCreatedByTab.vue
  components/torrent/TorrentCreationDateTab.vue
  components/torrent/TorrentDescriptionTab.vue
  components/torrent/TorrentEncodingTab.vue
Labels: Needs Rebase

#534 refactor:[#533] pass description from TorrentList
  components/torrent/TorrentList.vue
  components/torrent/TorrentListTorrentDetails.vue
Labels: Needs Rebase, Optimization

#544 fix:[#537] add --max-warnings=0 to package.json
  package.json
Labels: Needs Rebase

#543 fix:[#428] footer fix
  app.vue
Labels: Needs Rebase
